### ISSUE TITLE
[PE-D][Tester B] Inconsistent behavior with `group` function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-4/tp#88]
Using `group` with an index that is out of range sometimes will not cause an error whereas otherwise, it would

Steps to reproduce:
1. Delete the json file for the application.
2. Start the program instance.
3. There should only be 10 entries in the data set.
4. Entering `group 11` will cause nothing to happen (no output or errors).
5. Run `clear` to get any empty address book.
6. Entering `group 1` will cause nothing to happen (no output or errors).
7. Add a new participant with `add n/James Ho p/22224444 e/jamesho@example.com c/participant g/0`
8. `group 1` will cause nothing to happen.
9. Run `group 1 3` will cause contact 1 to change group.
10. Run `group 1` and there will be output.
12. Run `group 2` and there will be error.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: KohGuanZeh/ped#9

**Comment by julia-cp** [comment]
- descriptive title: :heavy_check_mark:
- enough details: :x: (no expected behavior, no screenshots)
- severity/type labels chosen are not too far off: :heavy_check_mark:
- non-confrontational tone: :heavy_check_mark:
- points out a potentially problematic behavior (or a good way to improve the product): :heavy_check_mark:
(multiple problems)

Not good report
